### PR TITLE
Update to Docsy v0.10.0

### PR DESCRIPTION
**Pull request by aykevl**
This adds support for light/dark mode, which I've waited for for a while. (I wish we could just make it automatic without menu entry, but this is already better than nothing).

There are a few small visual changes, which I think are generally an improvement:

  - Buttons are more square.
  - Links now have underscores, for accessibility reasons.
  - The ellipsis after "Read more..." on the home page is gone.
  - The copyright in the footer has changed slightly.

I did a quick browse through the website and couldn't find any breaking changes.

### CODE REVIEW

**Comment by aykevl** [comment]
And now it actually builds, after a few changes.
It looks like it uses a rather old build environment, @deadprogram do you know anything about that? I had to pick a different Go version because by default it would use Go 1.12.

**Comment by deadprogram** [comment]
We need to update the `netlify.toml` file:

I think this is what we need to have in there:

```toml
[build.environment]
  HUGO_VERSION = "0.127.0"
  GO_VERSION = "1.21"
  NODE_VERSION = "v20.x"
```

**Comment by aykevl** [comment]
@deadprogram I mean the build image: https://docs.netlify.com/configure-builds/overview/#build-image-selection
Apparently this can be configured from the web UI somewhere.

**Comment by deadprogram** [comment]
I think we are already using the latest image:

image

**Comment by aykevl** [comment]
Oh, okay. I think I saw Go 1.12 in there, which is kinda old, but 20.04 ships Go 1.13 so it's not that far off.
Then I think there's nothing we need to update.

(That means this PR is ready for merge in my opinion).

**Comment by deadprogram** [comment]
OK, now merging. Thanks for the update @aykevl

**Pull request merged**
