### PR TITLE
Add machine.CPUReset() doc

### PR DESCRIPTION
**Pull request by scottfeldman**
Add machine.SystemReset() to do a hard reset on device.  Only available for cortexm, currently.

### CODE REVIEW

**Comment by scottfeldman** [comment]
Reference https://github.com/tinygo-org/tinygo/pull/3595

**Comment by aykevl** [comment]
As it happens, I was thinking we needed this function today :)

I'm not sure about the name `SystemReset`, it might lead people to think it will reset more than just the microcontroller (like external devices).

What about `CPUReset`, analogous to `CPUFrequency`? But that is maybe too specific, as a reset will normally also reset I2C, SPI, pin states, etc.

> Not all chips support SystemReset.

I don't think we need to say this, because practically all microcontrollers support resetting the chip.

**Comment by scottfeldman** [comment]
> As it happens, I was thinking we needed this function today :)
> 
> I'm not sure about the name `SystemReset`, it might lead people to think it will reset more than just the microcontroller (like external devices).
> 
> What about `CPUReset`, analogous to `CPUFrequency`? But that is maybe too specific, as a reset will normally also reset I2C, SPI, pin states, etc.

CPUReset is good.  I'll update.

> > Not all chips support SystemReset.
> 
> I don't think we need to say this, because practically all microcontrollers support resetting the chip.

I don't have anything to test on other than contexm ARMs, so maybe we leave this comment and when someone updates it for the other cpus we can remove it?

**Comment by deadprogram** [comment]
@scottfeldman can you please rebase this against `dev`? Thank you!

**Pull request closed without merging**
