### PR TITLE
drivers: add page with links to TinyGo drivers repo, and list of drivers

### PR DESCRIPTION
**Pull request by deadprogram**
This PR adds a page with links to TinyGo drivers repo and list of supported drivers.

### CODE REVIEW

**Comment by aykevl** [comment]
Should we really include a list of drivers in the docs? I'm afraid it will turn stale very quickly.
We could also just provide a link to the drivers repo or the godoc list of drivers.

**Comment by deadprogram** [comment]
There are a couple of good reasons to add on the site itself. One is that i think few people are able to find this list currently. That is indicated in part by the large difference in Github stars between the main repo, and the drivers repo. Another is for search engine optimization.

**Comment by aykevl** [comment]
Okay. Perhaps it would be useful to add something like this? I'm afraid people will look at this list, conclude that a certain device is unsupported, and go elsewhere (or even duplicate work by writing their own).

> More drivers get added all the time. If your device isn't listed here, check the drivers repository.

**Comment by deadprogram** [comment]
Added some explanatory text/link pointing user to drivers repo.

**Pull request merged**
