### PR TITLE
concepts: add page with some porting hints

### PR DESCRIPTION
**Pull request by aykevl**
See for example https://github.com/tinygo-org/tinygo/issues/1284#issuecomment-1233151620

### CODE REVIEW

**Comment by deadprogram** [comment]
This is very helpful info. Just wondering if it should be under "Guides"?

**Comment by aykevl** [comment]
Yeah, that's probably a better place. I put it there because it seems similar to the FAQ.
No strong opinion from me.

**Comment by deadprogram** [comment]
A page that is a "how to" is likely a guide.

A page that is a "what is" is probably a concept.

At least that is what makes most sense to me.

**Comment by aykevl** [comment]
Okay, I've moved the page.

**Comment by deadprogram** [comment]
Great start, thank you @aykevl now merging.

**Pull request merged**
