### PR TITLE
Create tinygo-flash-errors.md

### PR DESCRIPTION
**Pull request by soypat**
Please take a look. Solves #203

### CODE REVIEW

**Comment by deadprogram** [comment]
Thanks for working on this @soypat I think this information would be better classified under "guides". Do you mind moving it over there?

**Comment by soypat** [comment]
No problem, done!

**Comment by soypat** [comment]
@deadprogram just squashed to minimize commit footprint

**Comment by deadprogram** [comment]
Thanks for working on this @soypat now merging.

**Pull request merged**
