### PR TITLE
better description

### PR DESCRIPTION
**Pull request by conejoninja**

### CODE REVIEW

**Comment by deadprogram** [comment]
@conejoninja this PR appears to fail build.

**Comment by conejoninja** [comment]
I saw it, but looks like it has nothing to do with the PR itself, how can I re-launch the build?

**Comment by deadprogram** [comment]
I think you need to rebase your branch against latest `dev`

**Comment by conejoninja** [comment]
ok, thanks!

**Comment by deadprogram** [comment]
Thanks for the fix @conejoninja now merging.

**Pull request merged**
