### PR TITLE
ide-integration: update to use proper GOROOT

### PR DESCRIPTION
**Pull request by aykevl**
This depends on https://github.com/tinygo-org/tinygo/pull/1362.

### CODE REVIEW

**Comment by sago35** [comment]
I tried this with vim.
This is a good and simple way for non-developers to check the source code.
I like that it's very easy to do.

However, a developer editing a machine package, for example, would need to know how to do the original.

**Comment by aykevl** [comment]
The cached GOROOT will contain symbolic links, so any edit to the machine package is also an edit to the cached GOROOT. So, this also works for developers of TinyGo.

You only need to change the settings with uncommon updates, such as when you move the TinyGo location or when you update the Go version.

**Comment by sago35** [comment]
Cool!

**Comment by deadprogram** [comment]
Is this ready to move out of draft yet?

**Comment by sago35** [comment]
This approach only works with recent dev branches.
I think it won't be possible to merge into a release branch until tinygo 0.15 is released.

**Comment by sago35** [comment]
@deadprogram  @aykevl 
tinygo 0.15 has been released, so I guess it's now mergeable.

**Comment by deadprogram** [comment]
OK, merging. Thanks!

**Pull request merged**
