### PR TITLE
Update linux.md for ArchLinux

### PR DESCRIPTION
**Pull request by wingedrhino**
Updated links for ArchLinux, since it is now in the community repository

### CODE REVIEW

**Comment by deadprogram** [comment]
@johanbrandhorst is this correct?

**Review by johanbrandhorst — CHANGES_REQUESTED** [review]
There are actually two versions - thank you for adding a link to the source-built one, but I think we should also include a link to the binary version (which is the one we control). Could you please add back the old one, in addition to this new one?

**Comment by deadprogram** [comment]
This PR is out of date with the current site structure, but is the info in it still needing to be added?

**Comment by ysoldak** [comment]
I propose close this PR, @deadprogram 
The change [released already](https://github.com/tinygo-org/tinygo-site/blob/release/content/getting-started/install/linux.md#arch-linux).

**Pull request closed without merging**
