### PR TITLE
Simplify use of docsy module

### PR DESCRIPTION
**Pull request by deining**
This PR remove module `github.com/google/docsy/dependencies` which is not needed any more.
It also brings `README.md` up to date.
It also bumps various dependencies to their latest versions.

### CODE REVIEW

**Comment by deadprogram** [comment]
@deining thank you very much for this update. I notice that there is some issue with an unpopulated iframe at the very bottom of the page in the preview site at https://deploy-preview-417--tinygo.netlify.app/

What do you think?

**Comment by deining** [comment]
> @deining thank you very much for this update.

You are welcome!

> I notice that there is some issue with an unpopulated iframe at the very bottom of the page in the preview site at https://deploy-preview-417--tinygo.netlify.app/
> What do you think?

Don't be deceived here, this iframe is an artefact which is present only in Netlify preview, you won't see in the deployed site.
If you scroll inside this iframe, you get an indication that this artefact is introduced from Netlify:

grafik

**Comment by deining** [comment]
Have a look [here](https://deploy-preview-2071--docsydocs.netlify.app/):

grafik

That's how this iframe is supposed to look like. No idea why it doesn't show up like that in the preview of the tinygo site.

**Comment by deadprogram** [comment]
Thanks for the clarification @deining now merging.

**Pull request merged**
