### PR TITLE
Add integration for Vim and Neovim with plugins

### PR DESCRIPTION
**Pull request by pcolladosoto**
This commit strives to add information on existing Vim and Neovim plugins integrating TinyGo with their respective LSP implementations. Links to both plugins as well as a bare-bones description on how they can be leveraged is also included.

If there's anything else that should be added feel more than free to ask away!

Thanks a ton for your time.

### CODE REVIEW

**Review by sago35 — APPROVED** [review]
LGTM

You created the TinyGo plugin for Neovim.
Excellent.

**Comment by pcolladosoto** [comment]
Great! Thanks a ton for the kind words 😸

**Review by soypat — APPROVED** [review]
LGTM!

**Comment by soypat** [comment]
@pcolladosoto and @sago35 Thanks for the contribution and review, respectively!

**Pull request merged**
