### PR TITLE
guides/embedded: add resources page

### PR DESCRIPTION
**Pull request by deadprogram**
This PR adds a new section for guides/embedded with a new resources page with links to some of the official resources for embedded development.

### CODE REVIEW

**Comment by aykevl** [comment]
While these are good suggestions, I think they could be a bit more specific. For example, for using the internal flash of a device it would be much more useful to point to an actual example of how to do that.

Also, mostly unrelated to this PR: we don't have a section for the new embedded flash API in the machine package documentation. It would be great to have it included in the documentation.

**Comment by deadprogram** [comment]
This branch requires that #363 be merged first, and then this branch rebased.

**Comment by deadprogram** [comment]
> While these are good suggestions, I think they could be a bit more specific. For example, for using the internal flash of a device it would be much more useful to point to an actual example of how to do that.

This PR is a starting point for more docs on these subjects. Right now there is no mention of them anywhere on the site, so it is at least an improvement. A future PR or PRs can add more detail.

**Review by aykevl — APPROVED** [review]

**Comment by deadprogram** [comment]
Merging to use as basis for some further changes in the new section. Thanks for review @aykevl

**Pull request merged**
