### PR TITLE
docs: add tau as runtime for tinygo wasm modules

### PR DESCRIPTION
**Pull request by samyfodil**

### CODE REVIEW

**Comment by deadprogram** [comment]
@samyfodil I think this might be better as an addition to https://github.com/tinygo-org/awesome-tinygo what do you think?

**Comment by samyfodil** [comment]
@deadprogram Just like extism, tau runs wasm modules compiled with tinygo. it also uses tinygo as default wasm compiler for go. This is why I thought adding it here.
I don't think it really fits in [awesome-tinygo](https://github.com/tinygo-org/awesome-tinygo) because tau itself can't be compiled with tinygo.

**Comment by deadprogram** [comment]
In that case, please keep the list in alpha order.

**Comment by samyfodil** [comment]
@deadprogram done :+1:

**Comment by deadprogram** [comment]
Thanks for the update @samyfodil now squash/merging.

**Pull request merged**
