### PR TITLE
Add platform specific installation links in getting started page

### LINKED ISSUE #27: Add link to platform specific installations in getting started
Currently the links are on the left navigation bar. I think it would be great to have the links on this page too - https://github.com/tinygo-org/tinygo-site/blob/master/content/getting-started/_index.md 

I will raise a PR for the same?

### PR DESCRIPTION
**Pull request by karuppiah7890**
Fix #27

### CODE REVIEW

**Comment by justinclift** [comment]
Tested here in a local installation, the links all work fine, so this looks good to me. :smile:

**Comment by deadprogram** [comment]
Moved to `dev` branch so it get picked up with all the other changes there on next release.

Now merging, thank you!

**Comment by deadprogram** [comment]
Actually, never mind, will rebase back to dev if needed. Merging to master.

**Comment by justinclift** [comment]
Merge it into both?

**Pull request merged**
