### PR TITLE
docs/guides: add pages for macOS and Windows

### PR DESCRIPTION
**Pull request by deadprogram**
This PR adds pages for macOS and Windows to the `docs/guides` section.

### CODE REVIEW

**Comment by aykevl** [comment]
This seems fine by me, but what about merging the three OS pages? Because although Linux is probably the one with the best support, from a user perspective all you need to know is that `GOOS` and `GOARCH` work the way you'd expect from the `go` toolchain.

**Comment by deadprogram** [comment]
> what about merging the three OS pages?

I think we have some OS specific information that would prove useful, and this gives us a place to put it.

For example, explaining that https://github.com/aykevl/macos-minimal-sdk is used for macOS. Which perhaps should be under the TinyGo org?

**Comment by aykevl** [comment]
> For example, explaining that https://github.com/aykevl/macos-minimal-sdk is used for macOS.

Yeah, maybe. It's not relevant to users in most cases, but when you are using CGo then it probably is.

**Comment by aykevl** [comment]
> Which perhaps should be under the TinyGo org?

Yeah, I've transferred it just now.

**Pull request merged**
