### PR TITLE
Fix link to DFU Description.

### PR DESCRIPTION
**Pull request by trichner**
The trailing ) broke the link, added a space to help markdown a bit.

### CODE REVIEW

**Comment by deadprogram** [comment]
Perhaps rewording this would be better, e.g.

> Flashing this board using its DFU bootloader can be a bit cumbersome, but it is possible - without requiring an external programmer - by pulling the B0 pin high (you can use the board's 3.3V output pin) at bootup when connected to host PC via USB. This puts the device in bootloader mode.
> For more information see Adafruit docs at https://learn.adafruit.com/adafruit-stm32f405-feather-express/dfu-bootloader-details
```

**Comment by trichner** [comment]
> Perhaps rewording this would be better, e.g.
> 
> > Flashing this board using its DFU bootloader can be a bit cumbersome, but it is possible - without requiring an external programmer - by pulling the B0 pin high (you can use the board's 3.3V output pin) at bootup when connected to host PC via USB. This puts the device in bootloader mode.
> > For more information see Adafruit docs at https://learn.adafruit.com/adafruit-stm32f405-feather-express/dfu-bootloader-details

fair point, I now took your suggestion and actually linked the text instead of showing the entire ugly URL (consistent what exists further above in the document).

**Comment by trichner** [comment]
Any interest in getting it fixed? I think I addressed all the feedback.

**Comment by trichner** [comment]
Ping?

**Comment by deadprogram** [comment]
Thanks for the reminder @trichner now merging.

**Pull request merged**
