### PR TITLE
getting-started: add docs for building TinyGo on Windows

### PR DESCRIPTION
**Pull request by aykevl**
This is probably missing something but it's better than nothing. Most importantly: it may require adding some paths to the `Path` environment variable and I'm not entirely sure whether MinGW-w64 works (but installing MinGW-w64 is easier than TDM-GCC which I did test). I think it should work because MinGW is installed on the hosted Azure CI agents.

I've also fixed some errors in the macos and linux guide.

EDIT: also note that this was my first time successfully building TinyGo on Windows. Previously I always did it on Azure CI.

### CODE REVIEW

**Comment by sago35** [comment]
I have created a PR #85 for this pr.

**Comment by sago35** [comment]
For better reproducibility, it might be better to prepare package.config as follows and fix the version. When I tried it yesterday, the version looked like this

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="cmake" version="3.17.2" />
  <package id="git" version="2.26.2" />
  <package id="golang" version="1.14.1" />
  <package id="make" version="4.3" />
  <package id="mingw" version="8.1.0" />
  <package id="ninja" version="1.10.0" />
  <package id="python2" version="2.7.18" />
</packages>
```

**Comment by sago35** [comment]
Other than what I wrote above, I think it's good.

**Comment by aykevl** [comment]
I do not think pinning specific versions is very helpful. The exact version should not matter a lot, and we do no specify package versions for other operating systems either. They will also quickly get out of date.

Specifically for Python: as mentioned in #85, Python 3 has worked for me (I agree the error messages is not very clear).

**Comment by aykevl** [comment]
(I should update this PR to just install MinGW)

**Comment by deadprogram** [comment]
> (I should update this PR to just install MinGW)

agreed.

**Comment by aykevl** [comment]
I have updated this to specify MinGW instead.

**Comment by deadprogram** [comment]
Merging.

**Pull request merged**
