### PR TITLE
boards: add PyGamer, WioTerminal, XIAO to supported boards

### PR DESCRIPTION
**Pull request by sago35**

### CODE REVIEW

**Comment by sago35** [comment]
I have confirmed that I can do make.

```
go run . arduino arduino-mega2560 arduino-nano arduino-nano33 bluepill circuitplay-bluefruit circuitplay-express clue_alpha digispark feather-m0 feather-m4 gameboy-advance hifive1b itsybitsy-m0 itsybitsy-m4 metro-m4-airlift microbit nrf528
40-mdk nucleo-f103rb particle-argon particle-boron particle-xenon pca10031 pca10040 pca10056 pinetime-devkit0 pybadge pygamer pyportal reelboard stm32f4disco trinket-m0 wioterminal x9pro xiao
Generating documentation for: arduino
Generating documentation for: arduino-mega2560
Generating documentation for: arduino-nano
Generating documentation for: arduino-nano33
Generating documentation for: bluepill
Generating documentation for: circuitplay-bluefruit
Generating documentation for: circuitplay-express
Generating documentation for: clue_alpha
Generating documentation for: digispark
Generating documentation for: feather-m0
Generating documentation for: feather-m4
Generating documentation for: gameboy-advance
Generating documentation for: hifive1b
Generating documentation for: itsybitsy-m0
Generating documentation for: itsybitsy-m4
Generating documentation for: metro-m4-airlift
Generating documentation for: microbit
Generating documentation for: nrf52840-mdk
Generating documentation for: nucleo-f103rb
Generating documentation for: particle-argon
Generating documentation for: particle-boron
Generating documentation for: particle-xenon
Generating documentation for: pca10031
Generating documentation for: pca10040
Generating documentation for: pca10056
Generating documentation for: pinetime-devkit0
Generating documentation for: pybadge
Generating documentation for: pygamer
Generating documentation for: pyportal
Generating documentation for: reelboard
Generating documentation for: stm32f4disco
Generating documentation for: trinket-m0
Generating documentation for: wioterminal
Generating documentation for: x9pro
Generating documentation for: xiao
```

**Comment by aykevl** [comment]
Can you also add the newly generated files? The tinygo.org website is entirely static so can't run this before deploying.

**Comment by sago35** [comment]
@aykevl 
I recreated machine/*.md and pushed it.
The source code when it was created is as follows.

https://github.com/tinygo-org/tinygo/commits/aa3481e06a9615f75b3c9283cfbd0d447c1fef1a

**Comment by aykevl** [comment]
Thank you!

**Pull request merged**
