### PR TITLE
Add Return Value to "func add()"

### PR DESCRIPTION
**Pull request by pfandzelter**
Will not compile otherwise.

### CODE REVIEW

**Comment by aykevl** [comment]
This looks good to me. Thank you for the fix!

@deadprogram I changed the base to dev, but when I did that a new commit appeared. Apparently one commit has been merged into the master branch instead of the dev branch (while I merged other commits into the dev branch). I'm not sure what's best to do now? Rebasing this PR on top of dev would perhaps be the cleanest option.

**Comment by deadprogram** [comment]
Agreed, that is probably easiest.

**Comment by pfandzelter** [comment]
There is actually a bit more on this page that doesn't quite add up or would need extension. I will try to extend the documentation here a bit when I can

**Comment by deadprogram** [comment]
For now I will just merge this PR, and we can figure out the rest from there in additional PRs.

Thank you @pfandzelter

**Pull request merged**
